Research.Eng : Soft.Eng
	@echo MS
	@echo Research.Eng
Soft.Eng : IIT
	@echo Soft.Eng
MS : IIT
	@echo MS
IIT : JEE
	@echo IIT
Hard.Eng : NIT
	@echo NIT
NIT : JEE
	@echo NIT
JEE : MPC
	@echo JEE
MPC : school
	@echo MPC
IVF.spec : Gynic 
	@echo MD
	@echo IVF.spec
Gynic : AIIMS
	@echo Gynic
ENT : AIIMS
	@echo ENT
MD : AIIMS
	@echo MD
AIIMS : NEET
	@echo AIIMS
Dentist : CMC
	@echo Dentist
CMC : NEET
	@echo CMC
NEET : BiPc
	@echo NEET
BiPc : school
	@echo BiPc
school :
	@echo school
